### ISSUE TITLE
I have managed to get Intel+Nvidia(HDMI) working in High Sierra (10.13.6)

### ISSUE THREAD

**Issue by themostunique** [cedric-bour/Acer-VN7-793g-Hackintosh#1]
1. Install Nvidia Web Drivers
2. Remove SSDT-GFX.aml
3. Inject Intel + ig-platform-id=0x59120000
4. System Parameters: NvidiaWeb=True

Current Problems:
Laptop Screen doesn't work.
HDMI needs to replug after boot to recognize the screen.

[AcerDualScreen.zip](https://github.com/cedric-bour/Acer-VN7-793g-Hackintosh/files/3884709/AcerDualScreen.zip)

**Comment by cedric-bour** [comment]
Branch master work full (intel + HDMI but nvidia disable)

Please show me your information :
![Capture d’écran 2019-11-25 à 08 10 07](https://user-images.githubusercontent.com/56200539/69519737-08111800-0f5b-11ea-9d6c-e3e85ff15c0e.png)

**Comment by themostunique** [comment]
<img width="1920" alt="Screen Shot 2019-11-26 at 12 07 06 AM (2)" src="https://user-images.githubusercontent.com/19430907/69556961-b4491200-0fe0-11ea-9272-255a3cab6b30.png">

**Comment by cedric-bour** [comment]
Oh yes !
Please test with EFI master and just :
- Remove SSDT-GFX.aml
- System Parameters: NvidiaWeb=True

**Comment by cedric-bour** [comment]
[EFI.zip](https://github.com/cedric-bour/Acer-VN7-793g-Hackintosh/files/3888745/EFI.zip)
test with this

**Comment by themostunique** [comment]
> [EFI.zip](https://github.com/cedric-bour/Acer-VN7-793g-Hackintosh/files/3888745/EFI.zip)
> test with this

With correct SMBIOS (14,3), boot args are not needed.
It works for type-c display and hdmi(nvidia). The only problem is internal laptop display. Also, HDMI need replug after boot to detect.

**Comment by cedric-bour** [comment]
I have GTX 1050 Ti, It not compatible with macOS, I can't help you

**Comment by themostunique** [comment]
It is ok, I don't really use the internal screen. I would try to figure out how to disable (turn off the backlight)

**Comment by themostunique** [comment]
Laptop display now works by changing the ig-platform-id to 0x591b0000
