### ISSUE TITLE
Bios and settings

### ISSUE THREAD

**Issue by RiverFolf** [cedric-bour/Acer-VN7-793g-Hackintosh#1]
Hi, 
I tried several times to makes MacOS work on my laptop but i just can't do it 😕 
I was looking for someone who managed to make hackintosh work on a VN7-793g and here you are 😄 

I'll try it but i'm kinda stuck with my limited bios settings :/
How did you manage to tweak yours ? (i can only toggle SecureBoot) 
And what settings did you change? 🤔 

Thanks 👍

**Comment by cedricdu78** [comment]
Hi,

Me too, I have limited bios settings, but i can boot on clover.
Have you create usb and test boot ?

Regards,

**Comment by RiverFolf** [comment]
Booting on clover isn't actually an issue 
But booting the macos installer was something else 😕 
i'm following your readme right now 🤞

**Comment by RiverFolf** [comment]
![IMG_20200410_220806](https://user-images.githubusercontent.com/17952355/79019999-f467f600-7b77-11ea-9d29-6549b9a3f220.jpg)
I get this when i start the installer
I don't think it's even leaving Clover :confused:

**Comment by cedricdu78** [comment]
What version of macos Catalina have you installed on your usb key?
If you have external monitor or other, please disconnect all peripherals
Connect usb key to USB port 2.0

**Comment by RiverFolf** [comment]
I only have the USB key connected and no external monitor 
I downloaded the last Catalina version from the app store 
And I tried with 3 USB ports 
Maybe we don't have the same VN7-793G ? 🤔

**Comment by cedricdu78** [comment]
Intel core i5, HD 630 with GTX 1050 Ti, latest version of BIOS

I haven't test with last version of Catalina, I tested with 10.15.2
I can't test right now, maybe in one month

If you can download, test with Mojave (last version) or Catalina 10.15.2

**Comment by RiverFolf** [comment]
Same as me 😕 
I'll try mojave tomorrow i think

Thank you for your time !
I'll keep you informed 👌

**Comment by RiverFolf** [comment]
Mojave 10.14.4 is working perfectly for me 
But i can't use the last version of Final Cut Pro (10.14.6 😢)

Thanks ! 👍

**Comment by cedricdu78** [comment]
Good 👍
