### ISSUE TITLE
Pls help 

### ISSUE THREAD

**Issue by marcinkk** [cedric-bour/Acer-VN7-793g-Hackintosh#2]
Hey, how do you set the keys to adjust the screen brightness on a laptop keyboard ?? Right now it's fn + f12 and fn + key pause. My bootloader is opencore. In my laptop acer v3-371, the shortcut from adjusting the screen brightness on the keyboard is the shortcut fn + left arrow key and fn + arrow right key.

**Comment by cedricdu78** [comment]
Hi,
You can change in Preference System => Keyboard => Shortcuts => Screen

**Comment by marcinkk** [comment]
But how do you set the fn + left arrow or right arrow keys ??

**Comment by cedricdu78** [comment]
You can't with Preference System, maybe with SSDT or other, I not idea for this, sorry :)
Else choose others keys
